#!/bin/sh
app='ddns'
version="0.0.1"
sudo=""
if command -v sudo >/dev/null 2>&1; then
    sudo="sudo"
fi

case $1 in 
    base)
        $sudo docker build -t 9d77v/$app-base:$version -f Dockerfile.base .
        $sudo docker push 9d77v/$app-base:$version
       ;;
    deploy)
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        $sudo docker build -t 9d77v/$app:$IMAGE_TAG .
        $sudo docker push 9d77v/$app:$IMAGE_TAG
        $sudo docker build -t 9d77v/$app:arm64.$IMAGE_TAG -f Dockerfile.arm64 .
        $sudo docker push 9d77v/$app:arm64.$IMAGE_TAG
        ;;
esac  

